import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import fetch from 'node-fetch';

type Props = {
  stream: {
    data: [
      {
        fact: string;
      }
    ];
  };
};

const getStream = async () => {
  const res = await fetch(
    `https://catfact.ninja/facts?page=${Math.floor(Math.random() * 34) + 1}`
  );
  const data = await res.json();

  // Pass data to the page via props
  return data;
};

// This gets called on every request
export async function getStaticProps() {
  const stream = await getStream();

  // Pass data to the page via props
  return { props: { stream }, revalidate: 60 };
}

const Home = ({ stream }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Live Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Live Page</h1>
        {stream.data.map(({ fact }, index) => (
          <p key={index}>{fact}</p>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
